### ISSUE TITLE
Update and subscribe

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/react-flux-dash#12]
Ahora mismo tengo que hacer dos cosas cada vez que una vista se carga:
```
    componentDidMount(){
        //aqui me suscribo a los cambios del store
        this.entitySubscription = AdminStore.subscribe("fetch_entity", this.updateFromStore.bind(this));
        
        //aqui cargo el estado actual del store
        let eventStates = AdminStore.getState();
        if(typeof eventStates["fetch_entity"] === 'undefined') return null;
        this.updateFromStore(eventStates["fetch_entity"]);
    }
    
    updateFromStore(state){
        this.setState({
            entities: (state.entities) ? state.entities[this.props.match.params.entity_slug] : [],
            entitySlug: this.props.match.params.entity_slug,
            entityComponent: this.props.match.params.entity_slug+'Card'
        });
    }
```

Sera posible que cuando me subscriba el event "fetch_entity" se llame el handler una primera vez para no tener que estar todo el tiempo manejando los dos escenarios?

**Comment by alacret** [comment]
Si lo cambio tendrias que hacer esa misma validacion en todos los escenarios opuestos. Es posible hacerlo de esa manera, pero creo que son mas los casos en los que vas a tratar de esquivar el valor actual y esperar un valor, a los escenarios en los que no tienes valor y lo necesitas
