### ISSUE TITLE
The dispatcher is not working when "uglify webpack" plugin is used.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/react-flux-dash#2]

**Comment by alesanchezr** [comment]
@alacret chamo esto de pana es un peo heavy.

**Comment by alesanchezr** [comment]
creo que ya esta funcionando... me puse a debuggear y no esta dando  mas, no se q pueda ser q es intermitente.

**Comment by alesanchezr** [comment]
@alacret found the error, we cannot realy on this.contructor.name because the webpack uglify plugin changes the names of all the classes.
https://github.com/4GeeksAcademy/react-flux-dash/blob/413bef9406fc83dc6d075fc95fb58d03f5dd5908/src/index.js#L58

**Comment by alacret** [comment]
Esto no parece ser el problema, una subclase usa su nombre y no del padre, asi que no impora si uglify cambia el nombre de la clase PAdre, la clase hija va a chequear bien con esto.

Que valores te da el ejemplo que has estado haciendo?

**Comment by alesanchezr** [comment]
Revisa para que veas, todos constructores ahora se llaman "t", es decir:
```js
this.constructor.name === 't'
```
Para que esto deje de pasar supuestamente hay que decirle al webpack uglify esta configuracion:
```js
        new UglifyJSPlugin({
            uglifyOptions: {
                mangle: {
                    keep_classnames: true
                }
            }
        }),
```
Pero tampoco me esta functionando, tengo como 5 horas intentando lograr que uglify ignore los nombres de las clases.

**Comment by alacret** [comment]
Voy a trabajar mejor en la version nueva, y mantenemos esa sin el uglify
