### ISSUE TITLE
Error should appear if trying to dispatch to an inexistent store

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/react-flux-dash#4]
When trying to dispatch to the wrong store like:
```
this.dispatch('QuizStore.setQuiz', { quiz });
```
If the **QuizStore** does not exists it should give me an error.

Right now is silently fails and students don't know why it's not dispatching.

**Comment by alesanchezr** [comment]
@alacret esto esta confundiendo a los alumnos

**Comment by alesanchezr** [comment]
@nachovz @alacret Tambien queria preguntarles si creen que deberiamos agregar un warning si notamos que el nombre del store no esta en notacion [UpperCamelCase](http://wiki.c2.com/?UpperCamelCase).

Porque ademas de que es una buena practica, la mayoria de los errores ocurren por eso.

**Comment by alacret** [comment]
Yo estoy buscando una manera mejor de hacer eso, no es muy intuitivo usar un String para hacer referencia a un objeto, tampoco lo es a veces usar un objeto y a veces una clase, no es straightforward de aprender por que el 99% no sabe la diferencia entre un objeto y una clase ni por que usas una o la otra y ahi se trancan. De hecho yo creo que es mejor que en las acciones exista un Dispatcher y las actions sean funciones que le envían mensajes, para ahi usar las funciones nada mas.
